CREATE TABLE `content_proposals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`proposalType` enum('conteudo','evento_rua') NOT NULL,
	`status` enum('pendente','aprovado','rejeitado') NOT NULL DEFAULT 'pendente',
	`title` varchar(255) NOT NULL,
	`description` text,
	`notes` text,
	`suggestedDate` timestamp NOT NULL,
	`contentType` enum('reels','carrossel','video','story','imagem'),
	`objective` varchar(255),
	`caption` text,
	`hashtags` text,
	`referenceUrls` text,
	`eventType` enum('caminhada','reuniao','panfletagem','visita','debate','entrevista','show','outro'),
	`location` varchar(500),
	`neighborhood` varchar(255),
	`city` varchar(255) DEFAULT 'Brasília',
	`eventTime` varchar(5) DEFAULT '09:00',
	`endTime` varchar(5),
	`expectedAttendees` int DEFAULT 0,
	`proposedById` int NOT NULL,
	`proposedByName` varchar(255),
	`reviewedById` int,
	`reviewedByName` varchar(255),
	`reviewNotes` text,
	`convertedItemId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`reviewedAt` timestamp,
	CONSTRAINT `content_proposals_id` PRIMARY KEY(`id`)
);
