import mysql from 'mysql2/promise';

const conn = await mysql.createConnection(process.env.DATABASE_URL);

// ─── POSTS DE INSTAGRAM — ABRIL 2026 ─────────────────────────────────────────
const posts = [
  // Semana 1: 1–5 abril
  {
    title: "Reel: Buracos na W3 Sul — Quando vai ser resolvido?",
    scheduledDate: "2026-04-01 12:00:00",
    scheduledTime: "12:00",
    type: "reels",
    status: "published",
    objective: "Topo de funil — reconhecimento territorial",
    description: "Reel mostrando os buracos na W3 Sul com narração do Eduardo: 'Aqui na Asa Sul, a W3 está há 8 meses sem manutenção. O TCDF apontou R$ 2,3 milhões desviados do fundo de manutenção viária. Vou cobrar na CLDF.'",
    caption: "🚧 W3 Sul: 8 meses de abandono. R$ 2,3 milhões que deveriam ir para o asfalto sumiram. Eduardo Brandão vai cobrar na CLDF. Compartilha pra chegar em quem decide! 👇",
    hashtags: "#AsaSul #BrasíliaCidadeParque #MobilidadeUrbana #W3Sul #EduardoBrandão #CLDF2026",
    expectedReach: 8500,
    expectedLikes: 420,
    expectedComments: 38,
    slideCount: 1,
    notes: "Gravar às 7h da manhã para pegar o movimento. Usar estabilizador. Mostrar placa de rua para geolocalização.",
  },
  {
    title: "Carrossel: 5 problemas de mobilidade que o DF precisa resolver",
    scheduledDate: "2026-04-02 18:00:00",
    scheduledTime: "18:00",
    type: "carrossel",
    status: "published",
    objective: "Meio de funil — autoridade e proposta",
    description: "Carrossel com 6 slides: capa + 5 problemas (ciclovia Asa Norte, BRT Sudoeste, semáforos inteligentes, calçadas Cruzeiro, integração metrô-ônibus) com dados do DETRAN-DF e proposta de Eduardo para cada um.",
    caption: "5 problemas de mobilidade que o DF precisa resolver AGORA. Slide a slide, as propostas de Eduardo Brandão para Brasília se mover melhor 👉",
    hashtags: "#BrasíliaCidadeParque #MobilidadeUrbana #DF2026 #EduardoBrandão #Brasília",
    expectedReach: 6200,
    expectedLikes: 310,
    expectedComments: 45,
    slideCount: 6,
    notes: "Design: fundo escuro, verde campanha. Fonte grande para mobile. Último slide com CTA para seguir.",
  },
  {
    title: "Story: Bastidores da visita ao Hospital Regional da Asa Norte",
    scheduledDate: "2026-04-03 10:00:00",
    scheduledTime: "10:00",
    type: "story",
    status: "published",
    objective: "Topo de funil — humanização",
    description: "Sequência de stories mostrando a visita ao HRAN: fila de espera, conversa com pacientes (com autorização), entrevista rápida com enfermeira sobre falta de insumos.",
    caption: null,
    hashtags: null,
    expectedReach: 3200,
    expectedLikes: 180,
    expectedComments: 12,
    slideCount: 8,
    notes: "Pedir autorização prévia da direção do hospital. Não mostrar rostos de pacientes sem consentimento.",
  },
  {
    title: "Reel: Parque Olhos D'Água — Patrimônio ambiental em risco",
    scheduledDate: "2026-04-06 12:00:00",
    scheduledTime: "12:00",
    type: "reels",
    status: "published",
    objective: "Topo de funil — Brasília Cidade Parque",
    description: "Reel no Parque Olhos D'Água (Asa Norte) mostrando a nascente e a área de preservação. Eduardo fala sobre o projeto de lei para ampliar a proteção das nascentes do DF.",
    caption: "💧 Brasília tem 35 parques ecológicos. Mas quantos estão realmente protegidos? O Parque Olhos D'Água está ameaçado por construções irregulares. Eduardo Brandão tem um projeto para mudar isso. Assiste até o final! 🌿",
    hashtags: "#BrasíliaCidadeParque #MeioAmbiente #OlhosDAgua #AsaNorte #EduardoBrandão #Sustentabilidade",
    expectedReach: 11200,
    expectedLikes: 680,
    expectedComments: 72,
    slideCount: 1,
    notes: "Horário golden hour (17h-18h). Drone para mostrar a extensão do parque. Trilha sonora ambiente.",
  },
  {
    title: "Imagem: Citação — Gestão fiscal transparente é respeito ao cidadão",
    scheduledDate: "2026-04-07 08:00:00",
    scheduledTime: "08:00",
    type: "imagem",
    status: "published",
    objective: "Meio de funil — posicionamento",
    description: "Post de citação com frase de Eduardo sobre transparência fiscal, com fundo verde campanha e foto do candidato.",
    caption: "\"Gestão fiscal transparente não é favor — é obrigação. Cada real do contribuinte precisa de destino claro.\" — Eduardo Brandão\n\nAcompanha a campanha 👉 @eduardobrandaodf",
    hashtags: "#GestãoFiscal #Transparência #BrasíliaCidadeParque #EduardoBrandão #CLDF2026",
    expectedReach: 4100,
    expectedLikes: 290,
    expectedComments: 18,
    slideCount: 1,
    notes: "Usar template de citação padrão da campanha. Aprovação do candidato antes de publicar.",
  },
  // Semana 2: 7–12 abril
  {
    title: "Reel: Visita à Ceilândia — Saúde pública em colapso",
    scheduledDate: "2026-04-08 12:00:00",
    scheduledTime: "12:00",
    type: "reels",
    status: "published",
    objective: "Topo de funil — expansão territorial",
    description: "Reel na UBS da Ceilândia Norte mostrando a fila desde as 5h da manhã. Eduardo entrevista moradores sobre o tempo de espera médio (4h) e propõe o projeto de telemedicina para RAs periféricas.",
    caption: "⏰ 5h da manhã. Fila na UBS da Ceilândia. Mães com crianças doentes esperando 4 horas por uma consulta. Eduardo Brandão foi lá ver de perto — e tem proposta para mudar isso. 🏥",
    hashtags: "#Ceilândia #SaúdePública #DF2026 #EduardoBrandão #BrasíliaCidadeParque #Telemedicina",
    expectedReach: 14300,
    expectedLikes: 890,
    expectedComments: 124,
    slideCount: 1,
    notes: "Equipe de 2 pessoas. Câmera discreta. Chegar às 5h30. Entrevistar pelo menos 3 moradores.",
  },
  {
    title: "Carrossel: Orçamento do GDF 2026 — O que foi aprovado e o que falta",
    scheduledDate: "2026-04-09 18:00:00",
    scheduledTime: "18:00",
    type: "carrossel",
    status: "published",
    objective: "Meio de funil — autoridade fiscal",
    description: "Análise do orçamento do GDF 2026 aprovado na CLDF: saúde recebeu 18% a menos que o previsto, mobilidade 22% a menos, educação 9% a mais. Eduardo explica o que isso significa para o cidadão.",
    caption: "O orçamento do GDF 2026 foi aprovado. Mas você sabe o que foi cortado? Saúde: -18%. Mobilidade: -22%. Veja slide a slide o que muda na sua vida 👉",
    hashtags: "#GestãoFiscal #OrçamentoDF #CLDF #EduardoBrandão #BrasíliaCidadeParque #Transparência",
    expectedReach: 7800,
    expectedLikes: 445,
    expectedComments: 67,
    slideCount: 7,
    notes: "Dados do DODF e CLDF. Verificar com assessor jurídico antes de publicar. Infográficos claros.",
  },
  {
    title: "Reel: Ciclovia da Asa Norte — Projeto que pode mudar Brasília",
    scheduledDate: "2026-04-13 12:00:00",
    scheduledTime: "12:00",
    type: "reels",
    status: "review",
    objective: "Topo de funil — mobilidade sustentável",
    description: "Reel pedalando na ciclovia da Asa Norte com Eduardo, mostrando os trechos interrompidos e propondo a extensão até o Lago Norte. Dados: 12km de ciclovia descontinuada no Plano Piloto.",
    caption: "🚴 12km de ciclovia descontinuada no Plano Piloto. Eduardo Brandão pedalou e viu de perto. O projeto para conectar Asa Norte ao Lago Norte está pronto. Assiste! 🌿",
    hashtags: "#Ciclovia #AsaNorte #MobilidadeUrbana #BrasíliaCidadeParque #EduardoBrandão #Sustentabilidade",
    expectedReach: 9600,
    expectedLikes: 520,
    expectedComments: 58,
    slideCount: 1,
    notes: "Gravar no fim de tarde. Eduardo de bicicleta. Mostrar o mapa do trajeto proposto no final.",
  },
  // Semana 3: 14–19 abril
  {
    title: "Reel: Mobilidade Urbana — O BRT que nunca chegou ao Sudoeste",
    scheduledDate: "2026-04-14 12:00:00",
    scheduledTime: "12:00",
    type: "reels",
    status: "draft",
    objective: "Topo de funil — reconhecimento Sudoeste/Noroeste",
    description: "Reel no Sudoeste mostrando o ponto de ônibus superlotado às 7h. Eduardo fala sobre o projeto de extensão do BRT que tramita na CLDF há 3 anos sem votação.",
    caption: "🚌 Sudoeste, 7h da manhã. O BRT que foi prometido há 3 anos ainda não chegou. Eduardo Brandão vai cobrar a votação na CLDF. Compartilha! 👇",
    hashtags: "#Sudoeste #BRT #MobilidadeUrbana #BrasíliaCidadeParque #EduardoBrandão #CLDF2026",
    expectedReach: 8900,
    expectedLikes: 460,
    expectedComments: 52,
    slideCount: 1,
    notes: "Gravar às 7h. Mostrar lotação do ponto. Eduardo de terno.",
  },
  {
    title: "Carrossel: Brasília Cidade Parque — 5 propostas ambientais",
    scheduledDate: "2026-04-15 18:00:00",
    scheduledTime: "18:00",
    type: "carrossel",
    status: "draft",
    objective: "Meio de funil — proposta ambiental",
    description: "Carrossel apresentando as 5 propostas ambientais da campanha: proteção de nascentes, arborização urbana, coleta seletiva nas RAs, parques lineares, e corredor ecológico Cerrado.",
    caption: "🌿 Brasília tem o maior cerrado urbano do mundo. Eduardo Brandão tem 5 propostas para proteger esse patrimônio. Desliza e conhece 👉",
    hashtags: "#BrasíliaCidadeParque #MeioAmbiente #Cerrado #EduardoBrandão #Sustentabilidade #DF2026",
    expectedReach: 7200,
    expectedLikes: 390,
    expectedComments: 48,
    slideCount: 6,
    notes: "Fotos dos parques de Brasília. Paleta verde. Dados do IBRAM-DF.",
  },
  {
    title: "Reel: Reunião com moradores do Lago Norte",
    scheduledDate: "2026-04-16 19:00:00",
    scheduledTime: "19:00",
    type: "reels",
    status: "draft",
    objective: "Meio de funil — proximidade com eleitor",
    description: "Reel dos bastidores da reunião com moradores do Lago Norte: pauta foi segurança e preservação ambiental do Lago Paranoá. Eduardo ouve demandas e apresenta propostas.",
    caption: "📍 Lago Norte. Eduardo Brandão ouviu os moradores: segurança e preservação do Paranoá são as prioridades. Veja o que foi discutido 👇",
    hashtags: "#LagoNorte #Segurança #LagoParanoá #BrasíliaCidadeParque #EduardoBrandão",
    expectedReach: 5800,
    expectedLikes: 310,
    expectedComments: 34,
    slideCount: 1,
    notes: "Gravar abertura e fechamento da reunião. Pedir autorização dos participantes.",
  },
  {
    title: "Story: Bastidores do dia de campanha — Guará",
    scheduledDate: "2026-04-17 10:00:00",
    scheduledTime: "10:00",
    type: "story",
    status: "draft",
    objective: "Topo de funil — humanização territorial",
    description: "Sequência de stories do dia de panfletagem no Guará: equipe se preparando, distribuição de material, conversa com moradores, selfies com apoiadores.",
    caption: null,
    hashtags: null,
    expectedReach: 2800,
    expectedLikes: 160,
    expectedComments: 8,
    slideCount: 10,
    notes: "Stories espontâneos, não roteirizados. Mostrar a equipe. Usar localização do Guará.",
  },
  {
    title: "Imagem: Dia do Índio — Brasília e os povos originários do Cerrado",
    scheduledDate: "2026-04-19 09:00:00",
    scheduledTime: "09:00",
    type: "imagem",
    status: "draft",
    objective: "Topo de funil — datas comemorativas",
    description: "Post especial para o Dia do Índio (19/04) com foto do Cerrado e texto sobre os povos Kayapó e Xerente que habitavam o território do DF antes da construção de Brasília.",
    caption: "🌿 19 de abril — Dia dos Povos Indígenas. Brasília foi construída no coração do Cerrado, território ancestral dos povos Kayapó e Xerente. Proteger o Cerrado é honrar essa história. #BrasíliaCidadeParque",
    hashtags: "#DiaDosPovosIndígenas #Cerrado #BrasíliaCidadeParque #EduardoBrandão #MeioAmbiente",
    expectedReach: 6500,
    expectedLikes: 480,
    expectedComments: 42,
    slideCount: 1,
    notes: "Arte especial para data comemorativa. Aprovação do candidato obrigatória.",
  },
  // Semana 4: 20–26 abril
  {
    title: "Reel: Saúde no Cruzeiro — UPA superlotada há 6 meses",
    scheduledDate: "2026-04-21 12:00:00",
    scheduledTime: "12:00",
    type: "reels",
    status: "draft",
    objective: "Topo de funil — saúde pública",
    description: "Reel na UPA do Cruzeiro mostrando a superlotação. Eduardo entrevista pacientes e propõe a criação de 3 novas UBSs no Cruzeiro e Sudoeste para desafogar a UPA.",
    caption: "🏥 UPA do Cruzeiro: superlotada há 6 meses. Pacientes esperando 8 horas por atendimento. Eduardo Brandão tem proposta para resolver. Assiste! 👇",
    hashtags: "#Cruzeiro #SaúdePública #UPA #BrasíliaCidadeParque #EduardoBrandão #DF2026",
    expectedReach: 10200,
    expectedLikes: 590,
    expectedComments: 78,
    slideCount: 1,
    notes: "Gravar às 14h (pico de atendimento). Equipe discreta. Autorização da direção.",
  },
  {
    title: "Carrossel: Segurança pública no DF — Dados e propostas",
    scheduledDate: "2026-04-22 18:00:00",
    scheduledTime: "18:00",
    type: "carrossel",
    status: "draft",
    objective: "Meio de funil — segurança pública",
    description: "Carrossel com dados da SSP-DF sobre criminalidade em 2025 e as 4 propostas de Eduardo: câmeras de segurança integradas, policiamento comunitário, iluminação pública LED e programa de reintegração social.",
    caption: "📊 Crimes no DF cresceram 12% em 2025. Eduardo Brandão tem 4 propostas concretas para reverter esse quadro. Desliza e conhece 👉",
    hashtags: "#Segurança #DF2026 #BrasíliaCidadeParque #EduardoBrandão #CLDF2026",
    expectedReach: 8100,
    expectedLikes: 420,
    expectedComments: 56,
    slideCount: 5,
    notes: "Dados da SSP-DF e SSPDF. Verificar com assessor jurídico. Não usar imagens de violência.",
  },
  {
    title: "Reel: Parque da Cidade — O pulmão de Brasília precisa de cuidado",
    scheduledDate: "2026-04-24 12:00:00",
    scheduledTime: "12:00",
    type: "reels",
    status: "draft",
    objective: "Topo de funil — Brasília Cidade Parque",
    description: "Reel no Parque da Cidade mostrando áreas degradadas, lixo acumulado e equipamentos quebrados. Eduardo propõe o programa 'Parque Vivo' com manutenção mensal e revitalização.",
    caption: "🌳 O Parque da Cidade é o maior parque urbano da América Latina. Mas está abandonado. Eduardo Brandão propõe o programa Parque Vivo para cuidar do que é nosso. Compartilha! 🌿",
    hashtags: "#ParqueDaCidade #BrasíliaCidadeParque #MeioAmbiente #EduardoBrandão #Brasília",
    expectedReach: 12800,
    expectedLikes: 720,
    expectedComments: 89,
    slideCount: 1,
    notes: "Gravar no fim de semana com movimento. Mostrar famílias no parque. Golden hour.",
  },
  {
    title: "Carrossel: Resultados da semana — Planejamento 14–19 de abril",
    scheduledDate: "2026-04-25 18:00:00",
    scheduledTime: "18:00",
    type: "carrossel",
    status: "draft",
    objective: "Fundo de funil — engajamento e mobilização",
    description: "Carrossel mostrando os resultados da semana: reunião com moradores do Lago Norte, panfletagem no Guará, visita à UPA do Cruzeiro. Chamada para seguir e compartilhar.",
    caption: "📍 Uma semana de campanha em 5 slides. Lago Norte, Guará, Cruzeiro — Eduardo Brandão está em todo o DF. Segue e acompanha! 👉",
    hashtags: "#BrasíliaCidadeParque #EduardoBrandão #DF2026 #Campanha2026 #CLDF",
    expectedReach: 5400,
    expectedLikes: 320,
    expectedComments: 28,
    slideCount: 5,
    notes: "Usar fotos das ações da semana. Compilação rápida. CTA forte no último slide.",
  },
  {
    title: "Reel: Noroeste — O bairro mais novo de Brasília e seus desafios",
    scheduledDate: "2026-04-28 12:00:00",
    scheduledTime: "12:00",
    type: "reels",
    status: "draft",
    objective: "Topo de funil — expansão territorial Noroeste",
    description: "Reel no Noroeste mostrando a falta de equipamentos públicos: sem UBS, sem escola pública, sem parque. Eduardo propõe o projeto 'Noroeste Completo' para suprir essas demandas.",
    caption: "🏙️ Noroeste: o bairro mais novo de Brasília. Mas sem UBS, sem escola pública, sem parque. Eduardo Brandão tem o projeto Noroeste Completo. Assiste! 👇",
    hashtags: "#Noroeste #BrasíliaCidadeParque #EduardoBrandão #DF2026 #Brasília",
    expectedReach: 7600,
    expectedLikes: 390,
    expectedComments: 44,
    slideCount: 1,
    notes: "Gravar em dia útil pela manhã. Mostrar o contraste entre o bairro moderno e a falta de serviços.",
  },
  {
    title: "Carrossel: Balanço de abril — Campanha em números",
    scheduledDate: "2026-04-30 18:00:00",
    scheduledTime: "18:00",
    type: "carrossel",
    status: "draft",
    objective: "Fundo de funil — prestação de contas",
    description: "Carrossel com o balanço do mês de abril: RAs visitadas, moradores atendidos, posts publicados, seguidores ganhos, eventos realizados. Projeção para maio.",
    caption: "📊 Abril em números: 8 RAs visitadas, 1.200 moradores atendidos, 18 posts publicados. Obrigado por acompanhar! Maio vem com muito mais. Segue! 👉",
    hashtags: "#BrasíliaCidadeParque #EduardoBrandão #Campanha2026 #DF2026 #CLDF2026",
    expectedReach: 6800,
    expectedLikes: 410,
    expectedComments: 35,
    slideCount: 6,
    notes: "Usar dados reais do Instagram e do banco de dados da campanha. Aprovação do candidato.",
  },
];

// ─── EVENTOS DE RUA — ABRIL 2026 ──────────────────────────────────────────────
const events = [
  {
    title: "Caminhada pela W3 Sul — Mobilidade Urbana",
    description: "Caminhada pela W3 Sul para mostrar os problemas de mobilidade: buracos, calçadas quebradas, falta de ciclovia. Eduardo Brandão percorre 2km com moradores e equipe de campanha, ouvindo demandas e registrando para apresentar na CLDF.",
    type: "caminhada",
    status: "realizado",
    eventDate: "2026-04-01 07:00:00",
    eventTime: "07:00",
    endTime: "09:30",
    location: "W3 Sul, entre as quadras 506 e 516, Asa Sul, Brasília-DF",
    neighborhood: "Asa Sul",
    city: "Brasília",
    expectedAttendees: 40,
    actualAttendees: 52,
    notes: "Convidar moradores via grupo de WhatsApp. Levar câmera para registrar os problemas. Distribuir panfleto com proposta de mobilidade.",
    lat: -15.8267,
    lng: -47.9218,
  },
  {
    title: "Visita ao Hospital Regional da Asa Norte (HRAN)",
    description: "Visita institucional ao HRAN para ouvir diretores, médicos e pacientes sobre as condições de atendimento. Foco em: fila de espera, falta de insumos, condições das instalações. Eduardo apresenta proposta de telemedicina.",
    type: "visita",
    status: "realizado",
    eventDate: "2026-04-03 09:00:00",
    eventTime: "09:00",
    endTime: "11:30",
    location: "Hospital Regional da Asa Norte — SMHN Quadra 101, Área Especial, Asa Norte, Brasília-DF",
    neighborhood: "Asa Norte",
    city: "Brasília",
    expectedAttendees: 5,
    actualAttendees: 8,
    notes: "Agendar com a direção do hospital com antecedência. Levar assessor de imprensa. Não fotografar pacientes sem autorização.",
    lat: -15.7386,
    lng: -47.8989,
  },
  {
    title: "Panfletagem no Parque Olhos D'Água",
    description: "Panfletagem no Parque Olhos D'Água com distribuição de material sobre o projeto de proteção de nascentes. Equipe de 8 pessoas distribuindo panfletos para frequentadores do parque no fim de semana.",
    type: "panfletagem",
    status: "realizado",
    eventDate: "2026-04-05 08:00:00",
    eventTime: "08:00",
    endTime: "11:00",
    location: "Parque Ecológico Olhos D'Água — Av. L2 Norte, Asa Norte, Brasília-DF",
    neighborhood: "Asa Norte",
    city: "Brasília",
    expectedAttendees: 8,
    actualAttendees: 8,
    notes: "Levar 500 panfletos. Equipe de 8 voluntários. Usar colete da campanha.",
    lat: -15.7412,
    lng: -47.8876,
  },
  {
    title: "Visita à UBS da Ceilândia Norte",
    description: "Visita à Unidade Básica de Saúde da Ceilândia Norte para acompanhar o atendimento e ouvir moradores na fila desde as 5h. Eduardo registra as condições e propõe o projeto de telemedicina para RAs periféricas.",
    type: "visita",
    status: "realizado",
    eventDate: "2026-04-08 05:30:00",
    eventTime: "05:30",
    endTime: "08:00",
    location: "UBS Ceilândia Norte — QNN 13, Área Especial, Ceilândia Norte, Brasília-DF",
    neighborhood: "Ceilândia",
    city: "Brasília",
    expectedAttendees: 3,
    actualAttendees: 3,
    notes: "Chegar às 5h30. Câmera discreta. Entrevistar pelo menos 3 moradores com autorização.",
    lat: -15.8089,
    lng: -48.1012,
  },
  {
    title: "Reunião com Associação de Moradores do Lago Sul",
    description: "Reunião com a Associação de Moradores do Lago Sul para discutir preservação do Lago Paranoá, segurança e mobilidade. Eduardo apresenta propostas e ouve demandas específicas da RA.",
    type: "reuniao",
    status: "realizado",
    eventDate: "2026-04-10 19:00:00",
    eventTime: "19:00",
    endTime: "21:00",
    location: "Sede da Associação de Moradores do Lago Sul — SHIS QI 11, Lago Sul, Brasília-DF",
    neighborhood: "Lago Sul",
    city: "Brasília",
    expectedAttendees: 35,
    actualAttendees: 48,
    notes: "Levar material de apresentação. Projetor. Coffee break para os participantes.",
    lat: -15.8456,
    lng: -47.8734,
  },
  {
    title: "Caminhada pela Ciclovia da Asa Norte",
    description: "Eduardo Brandão percorre de bicicleta os 12km de ciclovia descontinuada da Asa Norte, mostrando os trechos interrompidos e propondo a extensão até o Lago Norte. Equipe de campanha e jornalistas convidados.",
    type: "caminhada",
    status: "realizado",
    eventDate: "2026-04-12 07:00:00",
    eventTime: "07:00",
    endTime: "10:00",
    location: "Ciclovia Asa Norte — início na Av. W3 Norte, Quadra 702, Asa Norte, Brasília-DF",
    neighborhood: "Asa Norte",
    city: "Brasília",
    expectedAttendees: 20,
    actualAttendees: 27,
    notes: "Levar bicicletas para Eduardo e equipe. Convidar jornalistas do Correio Braziliense e Metrópoles. Capacete obrigatório.",
    lat: -15.7298,
    lng: -47.8945,
  },
  {
    title: "Panfletagem no Sudoeste — BRT e Mobilidade",
    description: "Panfletagem no Sudoeste com foco no projeto de extensão do BRT. Equipe de 10 voluntários nos principais pontos de ônibus do bairro durante o horário de pico da manhã.",
    type: "panfletagem",
    status: "realizado",
    eventDate: "2026-04-14 06:30:00",
    eventTime: "06:30",
    endTime: "09:00",
    location: "Ponto de Ônibus SQSW 302, Sudoeste, Brasília-DF",
    neighborhood: "Sudoeste",
    city: "Brasília",
    expectedAttendees: 10,
    actualAttendees: 10,
    notes: "Levar 800 panfletos. Foco nos pontos de ônibus. Horário de pico: 6h30-8h30.",
    lat: -15.7934,
    lng: -47.9312,
  },
  {
    title: "Reunião com Moradores do Lago Norte",
    description: "Reunião aberta com moradores do Lago Norte para discutir segurança pública e preservação ambiental do Lago Paranoá. Eduardo apresenta propostas e ouve demandas da comunidade.",
    type: "reuniao",
    status: "realizado",
    eventDate: "2026-04-16 19:00:00",
    eventTime: "19:00",
    endTime: "21:00",
    location: "Centro Comunitário do Lago Norte — SHIN QL 10, Lago Norte, Brasília-DF",
    neighborhood: "Lago Norte",
    city: "Brasília",
    expectedAttendees: 50,
    actualAttendees: 63,
    notes: "Divulgar nas redes sociais 3 dias antes. Levar lista de presença. Coffee break.",
    lat: -15.7123,
    lng: -47.8567,
  },
  {
    title: "Panfletagem no Guará — Dia de Campanha",
    description: "Dia completo de panfletagem no Guará com equipe de 15 voluntários. Distribuição de material sobre todas as propostas da campanha nos principais pontos de circulação do bairro.",
    type: "panfletagem",
    status: "realizado",
    eventDate: "2026-04-17 07:00:00",
    eventTime: "07:00",
    endTime: "12:00",
    location: "Feira do Guará — Av. Central, Guará I, Brasília-DF",
    neighborhood: "Guará",
    city: "Brasília",
    expectedAttendees: 15,
    actualAttendees: 18,
    notes: "Levar 1.500 panfletos. Equipe de 15 voluntários. Eduardo presente das 9h às 11h.",
    lat: -15.8312,
    lng: -48.0123,
  },
  {
    title: "Visita à UPA do Cruzeiro",
    description: "Visita à UPA do Cruzeiro para registrar a superlotação e ouvir pacientes e profissionais de saúde. Eduardo propõe a criação de 3 novas UBSs no Cruzeiro e Sudoeste para desafogar a UPA.",
    type: "visita",
    status: "confirmado",
    eventDate: "2026-04-21 14:00:00",
    eventTime: "14:00",
    endTime: "16:00",
    location: "UPA Cruzeiro — SHCES Quadra 803, Cruzeiro, Brasília-DF",
    neighborhood: "Cruzeiro",
    city: "Brasília",
    expectedAttendees: 4,
    actualAttendees: null,
    notes: "Agendar com a direção. Câmera discreta. Horário de pico: 14h. Não fotografar pacientes sem autorização.",
    lat: -15.7923,
    lng: -47.9456,
  },
  {
    title: "Debate sobre Segurança Pública — Asa Sul",
    description: "Debate aberto sobre segurança pública na Asa Sul com moradores, representantes da PM-DF e Eduardo Brandão. Pauta: câmeras de segurança, policiamento comunitário e iluminação pública.",
    type: "debate",
    status: "confirmado",
    eventDate: "2026-04-23 19:00:00",
    eventTime: "19:00",
    endTime: "21:30",
    location: "Centro Comunitário da Asa Sul — SQS 308, Bloco A, Asa Sul, Brasília-DF",
    neighborhood: "Asa Sul",
    city: "Brasília",
    expectedAttendees: 80,
    actualAttendees: null,
    notes: "Convidar representante da PM-DF e da SSP-DF. Moderador neutro. Transmissão ao vivo no Instagram.",
    lat: -15.8234,
    lng: -47.9123,
  },
  {
    title: "Caminhada no Parque da Cidade — Brasília Cidade Parque",
    description: "Caminhada no Parque da Cidade com Eduardo Brandão e apoiadores para mostrar as áreas degradadas e lançar o programa 'Parque Vivo'. Convidar imprensa e influenciadores locais.",
    type: "caminhada",
    status: "planejado",
    eventDate: "2026-04-26 08:00:00",
    eventTime: "08:00",
    endTime: "11:00",
    location: "Parque da Cidade Sarah Kubitschek — Eixo Monumental, Brasília-DF",
    neighborhood: "Asa Sul",
    city: "Brasília",
    expectedAttendees: 100,
    actualAttendees: null,
    notes: "Divulgar 1 semana antes. Convidar influenciadores ambientais de Brasília. Levar material do programa Parque Vivo.",
    lat: -15.8012,
    lng: -47.9234,
  },
  {
    title: "Visita ao Noroeste — Levantamento de Demandas",
    description: "Visita ao Noroeste para levantamento de demandas dos moradores: falta de UBS, escola pública e parque. Eduardo apresenta o projeto 'Noroeste Completo' e ouve sugestões da comunidade.",
    type: "visita",
    status: "planejado",
    eventDate: "2026-04-28 10:00:00",
    eventTime: "10:00",
    endTime: "12:30",
    location: "Praça Central do Noroeste — SQNW 311, Noroeste, Brasília-DF",
    neighborhood: "Noroeste",
    city: "Brasília",
    expectedAttendees: 30,
    actualAttendees: null,
    notes: "Divulgar no grupo de WhatsApp do Noroeste. Levar questionário de demandas para os moradores preencherem.",
    lat: -15.7456,
    lng: -47.9567,
  },
  {
    title: "Reunião de Encerramento de Abril — Equipe de Campanha",
    description: "Reunião interna de encerramento do mês de abril com toda a equipe de campanha: balanço de resultados, lições aprendidas e planejamento estratégico para maio.",
    type: "reuniao",
    status: "planejado",
    eventDate: "2026-04-30 18:00:00",
    eventTime: "18:00",
    endTime: "20:00",
    location: "Sede da Campanha Eduardo Brandão — SCS Quadra 2, Bloco C, Asa Sul, Brasília-DF",
    neighborhood: "Asa Sul",
    city: "Brasília",
    expectedAttendees: 20,
    actualAttendees: null,
    notes: "Reunião interna. Preparar relatório de resultados de abril. Definir metas de maio.",
    lat: -15.7989,
    lng: -47.8923,
  },
];

// ─── INSERÇÃO NO BANCO ────────────────────────────────────────────────────────
console.log('Inserindo posts...');
for (const post of posts) {
  await conn.execute(
    `INSERT INTO instagram_posts 
     (title, scheduledDate, scheduledTime, type, status, objective, description, caption, hashtags, notes, expectedReach, expectedLikes, expectedComments, slideCount)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      post.title, post.scheduledDate, post.scheduledTime, post.type, post.status,
      post.objective ?? null, post.description ?? null, post.caption ?? null,
      post.hashtags ?? null, post.notes ?? null,
      post.expectedReach ?? 0, post.expectedLikes ?? 0, post.expectedComments ?? 0,
      post.slideCount ?? 1,
    ]
  );
}
console.log(`✅ ${posts.length} posts inseridos`);

console.log('Inserindo eventos de rua...');
for (const ev of events) {
  await conn.execute(
    `INSERT INTO street_events 
     (title, description, type, status, eventDate, eventTime, endTime, location, neighborhood, city, expectedAttendees, actualAttendees, notes, lat, lng)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      ev.title, ev.description ?? null, ev.type, ev.status,
      ev.eventDate, ev.eventTime ?? null, ev.endTime ?? null,
      ev.location, ev.neighborhood ?? null, ev.city ?? 'Brasília',
      ev.expectedAttendees ?? 0, ev.actualAttendees ?? null,
      ev.notes ?? null, ev.lat ?? null, ev.lng ?? null,
    ]
  );
}
console.log(`✅ ${events.length} eventos inseridos`);

await conn.end();
console.log('🎉 Seed de abril concluído!');
